# Generated by Django 5.1.1 on 2024-10-25 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Estado', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tipo', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ubicacion', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FechaEntrega', models.DateField(null=True)),
                ('Cantidad', models.IntegerField(max_length=15)),
                ('FechaCaducidad', models.DateField(null=True)),
                ('IdEstado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tablas.estado')),
                ('IdProducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tablas.producto')),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='IdTipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tablas.tipo'),
        ),
        migrations.AddField(
            model_name='producto',
            name='IdUbicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tablas.ubicacion'),
        ),
    ]
