# Generated by Django 5.1.1 on 2024-10-25 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='Cantidad',
            field=models.IntegerField(),
        ),
    ]
