# Generated by Django 5.1.1 on 2024-11-01 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tablas', '0003_alter_lote_fechacaducidad_alter_lote_fechaentrega'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estado',
            old_name='Estado',
            new_name='estado',
        ),
        migrations.RenameField(
            model_name='lote',
            old_name='Cantidad',
            new_name='cantidad',
        ),
        migrations.RenameField(
            model_name='lote',
            old_name='IdEstado',
            new_name='estado',
        ),
        migrations.RenameField(
            model_name='lote',
            old_name='FechaCaducidad',
            new_name='fechacaducidad',
        ),
        migrations.RenameField(
            model_name='lote',
            old_name='FechaEntrega',
            new_name='fechaentrega',
        ),
        migrations.RenameField(
            model_name='lote',
            old_name='IdProducto',
            new_name='producto',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='Nombre',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='IdTipo',
            new_name='tipo',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='IdUbicacion',
            new_name='ubicacion',
        ),
        migrations.RenameField(
            model_name='tipo',
            old_name='Tipo',
            new_name='tipo',
        ),
        migrations.RenameField(
            model_name='ubicacion',
            old_name='Ubicacion',
            new_name='ubicacion',
        ),
    ]
