# Generated by Django 5.1.1 on 2024-11-09 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablas', '0005_lote_proveedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='proveedor',
            field=models.CharField(default='', max_length=20),
        ),
    ]
